"""Convert assets/spleen-12x24.bdf into spleen_12x24.py for main.py's text().

Glyphs are stored for framebuf.MONO_HLSB: each row is two bytes, leftmost
pixel in the top bit, so a 12x24 glyph takes 48 bytes. Covers printable ASCII.
"""
import os

ROOT = os.path.join(os.path.dirname(__file__), "..")
SRC = os.path.join(ROOT, "assets", "spleen-12x24.bdf")
OUT = os.path.join(ROOT, "spleen_12x24.py")
FIRST, LAST = 0x20, 0x7F


def parse(path):
    lines = iter(open(path).read().splitlines())
    width = height = ascent = None
    glyphs = {}
    for line in lines:
        key, _, rest = line.partition(" ")
        if key == "FONTBOUNDINGBOX":
            width, height, _, yoff = map(int, rest.split())
            ascent = height + yoff
        elif key == "ENCODING":
            code = int(rest)
        elif key == "BBX":
            bbx = tuple(map(int, rest.split()))
        elif key == "BITMAP":
            rows = []
            for row in lines:
                if row == "ENDCHAR":
                    break
                rows.append(int(row, 16))
            glyphs[code] = (bbx, rows)
    return width, height, ascent, glyphs


def cell(width, height, ascent, bbx, rows):
    """Place a glyph's bitmap rows in a width x height cell, as 16-bit rows."""
    w, h, xoff, yoff = bbx
    bits = (w + 7) // 8 * 8
    out = [0] * height
    top = ascent - (yoff + h)
    for r, value in enumerate(rows):
        y = top + r
        if 0 <= y < height:
            out[y] = (value << (16 - bits)) >> xoff & 0xFFFF
    return out


def main():
    width, height, ascent, glyphs = parse(SRC)
    assert width <= 16, "two bytes per row"
    data = bytearray()
    for code in range(FIRST, LAST):
        bbx, rows = glyphs.get(code, glyphs[ord("?")])
        for row in cell(width, height, ascent, bbx, rows):
            data += row.to_bytes(2, "big")
    with open(OUT, "w") as f:
        f.write("# Generated by tools/make_font.py from assets/spleen-12x24.bdf. Do not edit.\n")
        f.write("# Spleen (c) Frederic Cambus, BSD 2-Clause: see assets/spleen-LICENSE.\n")
        f.write("WIDTH = %d\nHEIGHT = %d\nFIRST = 0x%02X\nLAST = 0x%02X\n" % (width, height, FIRST, LAST))
        f.write("FONT = %r\n" % bytes(data))
    print("wrote", OUT, len(data), "bytes")


if __name__ == "__main__":
    main()
