"""Rasterise assets/claude-logo.svg into claude_logo.py as an RGB565 buffer for blit_buffer.

The SVG is a single filled path, so this parses the path, flattens it to a
polygon and fills it with supersampling for anti-aliased edges over black.
"""
import colorsys
import os
import re
import struct

ROOT = os.path.join(os.path.dirname(__file__), "..")
SIZE = 48
SUPERSAMPLE = 4


def parse_path(d):
    tokens = re.findall(r"[A-Za-z]|-?(?:\d+\.?\d*|\.\d+)", d)
    points, pos, i, cmd = [], (0.0, 0.0), 0, None
    start = pos

    def nums(n):
        nonlocal i
        vals = [float(t) for t in tokens[i:i + n]]
        i += n
        return vals

    while i < len(tokens):
        if tokens[i].isalpha():
            cmd = tokens[i]
            i += 1
            if cmd in "Zz":
                pos = start
                continue
        rel = cmd.islower()
        c = cmd.lower()
        x, y = pos
        if c in "ml":
            dx, dy = nums(2)
            pos = (x + dx, y + dy) if rel else (dx, dy)
            if c == "m":
                start = pos
                cmd = "l" if rel else "L"
            points.append(pos)
        elif c == "h":
            (v,) = nums(1)
            pos = (x + v if rel else v, y)
            points.append(pos)
        elif c == "v":
            (v,) = nums(1)
            pos = (x, y + v if rel else v)
            points.append(pos)
        elif c == "c":
            x1, y1, x2, y2, ex, ey = nums(6)
            if rel:
                x1, y1, x2, y2, ex, ey = x + x1, y + y1, x + x2, y + y2, x + ex, y + ey
            for s in range(1, 9):
                t = s / 8
                mt = 1 - t
                points.append((
                    mt ** 3 * x + 3 * mt * mt * t * x1 + 3 * mt * t * t * x2 + t ** 3 * ex,
                    mt ** 3 * y + 3 * mt * mt * t * y1 + 3 * mt * t * t * y2 + t ** 3 * ey,
                ))
            pos = (ex, ey)
        else:
            raise ValueError("unsupported path command " + cmd)
    return points


def inside(poly, px, py):
    hit = False
    j = len(poly) - 1
    for k in range(len(poly)):
        xi, yi = poly[k]
        xj, yj = poly[j]
        if (yi > py) != (yj > py) and px < (xj - xi) * (py - yi) / (yj - yi) + xi:
            hit = not hit
        j = k
    return hit


def main():
    svg = open(os.path.join(ROOT, "assets", "claude-logo.svg")).read()
    h, s, l = (float(v) for v in re.search(r"hsl\(([\d.]+),\s*([\d.]+)%,\s*([\d.]+)%\)", svg).groups())
    r, g, b = colorsys.hls_to_rgb(h / 360, l / 100, s / 100)
    poly = parse_path(re.search(r' d="([^"]+)"', svg).group(1))
    view = 100.0

    buf = bytearray()
    n = SUPERSAMPLE
    for row in range(SIZE):
        for col in range(SIZE):
            hits = sum(
                inside(poly, (col + (sx + 0.5) / n) * view / SIZE, (row + (sy + 0.5) / n) * view / SIZE)
                for sy in range(n) for sx in range(n)
            )
            a = hits / (n * n)
            rgb = (int(r * 255 * a), int(g * 255 * a), int(b * 255 * a))
            buf += struct.pack(">H", (rgb[0] & 0xF8) << 8 | (rgb[1] & 0xFC) << 3 | rgb[2] >> 3)

    with open(os.path.join(ROOT, "claude_logo.py"), "w") as f:
        f.write("# Generated by tools/make_logo.py from assets/claude-logo.svg (CC0). Do not edit.\n")
        f.write("WIDTH = %d\nHEIGHT = %d\n" % (SIZE, SIZE))
        f.write("COLOR = (%d, %d, %d)\n" % (round(r * 255), round(g * 255), round(b * 255)))
        f.write("BUFFER = %r\n" % bytes(buf))

    # ASCII preview for a quick sanity check.
    for row in range(0, SIZE, 2):
        print("".join(" .:#"[min(3, (buf[(row * SIZE + c) * 2] >> 3) // 8)] for c in range(SIZE)))


if __name__ == "__main__":
    main()
